# Generated by Django 2.1.7 on 2019-03-28 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 28, 16, 30, 4, 605862, tzinfo=utc)),
        ),
    ]
