# Generated by Django 2.1.7 on 2019-03-29 04:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190329_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_date', models.DateTimeField(default=datetime.datetime(2019, 3, 29, 4, 44, 47, 742801, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=200)),
                ('media', models.ImageField(blank=True, null=True, upload_to='media')),
                ('adress', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('info', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='media',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='published_date',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 4, 44, 47, 742143, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='picture'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Company'),
        ),
        migrations.AddField(
            model_name='comment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Company'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Advertisement'),
        ),
    ]
