# Generated by Django 2.1.7 on 2019-04-01 04:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190329_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='media',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_photo',
            field=models.ImageField(blank=True, null=True, upload_to='comment-photo'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 4, 4, 1, 520295, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 4, 4, 1, 520937, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 4, 4, 1, 519740, tzinfo=utc)),
        ),
    ]
