# Generated by Django 2.2 on 2019-04-09 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190409_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 6, 9, 10, 198613, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 6, 9, 10, 199628, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 9, 6, 9, 10, 197510, tzinfo=utc)),
        ),
    ]
